### ISSUE TITLE
Company Branded Tab

### ISSUE THREAD

**Issue by drrobotnik** [CaavaDesign/caava-helper#1]
# Roadmap
- [ ] Create Caava Tab
- [ ] Add BugHerd support widget that displays active bugs & status.
- [ ] Add company blog feed
- [ ] Include interface for client social integration
